### ISSUE TITLE
UnboundBL as official Plugin

### ISSUE THREAD

**Issue by ma-karai** [al-ec/UnboundBL#1]
Will this be in the official plugin section at somepoint?

**Comment by ma-karai** [comment]
bump?

**Comment by tworth04** [comment]
hoping as well

**Comment by alectrocute** [comment]
Hey, once I get it done, I'm sure it'll be an official plugin.

We've made some progress over on a different branch. I'll update this entire repo with the new code once it's ready. Keep watching!

**Comment by alectrocute** [comment]
@bott0r, @tworth04 I've just released the first stable version. This is currently pending to be added as an official plugin.

**Comment by ma-karai** [comment]
Awesomesauce

**Comment by ma-karai** [comment]
any news on this ?
