### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by tworth04** [al-ec/UnboundBL#2]
Hi,

Was very excited when you first announced it.  Was wondering if you had abandoned the project or if it's still being developed?

Really hoping for the latter :)

**Comment by alectrocute** [comment]
I'm slowly working on it, just so busy as of recent. I plan on getting back to it and finishing a working version by May of this year. Hopefully before then.

**Comment by alectrocute** [comment]
I've just released the first stable version, @tworth04!
