### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by nekoprog** [al-ec/UnboundBL#4]
Hello, I got chmod error file not found for this `chmod 755 /usr/local/opnsense/scripts/OPNsense/UnboundBL/data.sh`, where does data.sh come from?

**Comment by alectrocute** [comment]
Hey @nekoprog, `data.sh` is generated by OPNsense's templating engine. Try deleting the `+POST INSTALL` file, I think that may be the issue.

**Comment by nekoprog** [comment]
It works, thanks.

![capture1](https://user-images.githubusercontent.com/2550618/54524921-0b0c3f80-49ae-11e9-8787-711dfb3b5b24.png)
